### ISSUE TITLE
JSON5 sort

### ISSUE THREAD

**Issue by IAluI** [duniul/sort-jsonc#8]
The repository description says "sort JSONC/JSON5". But when I'm try to sort first example from https://spec.json5.org/ 
```
{
  // comments
  unquoted: 'and you can quote me on that',
  singleQuotes: 'I can use "double quotes" here',
  lineBreaks: "Look, Mom! \
No \\n's!",
  hexadecimal: 0xdecaf,
  leadingDecimalPoint: .8675309, andTrailing: 8675309.,
  positiveSign: +1,
  trailingComma: 'in objects', andIn: ['arrays',],
  "backwardsCompatible": "with JSON",
}
```
and have error "Unexpected token u".

Internally you use javascript object JSON for parsing. It seems to be unable to parse JSON5 even if you first extract the comments from JSON5.

**Comment by duniul** [comment]
You're right, my bad! 🙏 I initially experimented with supporting JSON5, but opted for just supporting JSONC since it solved my needs and was more straightforward (JSON5 does not have a good parser for keeping comment positions when sorting). Somehow I forgot to clean up the docs!

I've removed all mentions of JSON5 in the repo and in the latest release to avoid confusion.
